### ISSUE TITLE
NPM package does not have a LICENSE file

### ISSUE THREAD

**Issue by andyparisi** [codemod-com/filemod#19]
I am unable to procure intuita on my org's system because of a failure in this dependency. `1.1.0` appears to not have a license file.

NPM reflects as much https://www.npmjs.com/package/@intuita-inc/filemod

**Comment by grzpab** [comment]
@andyparisi hello, thank you for filing an issue, version 2.0.0 of `filemod` has the Apache-2.0 license and we just published it: https://www.npmjs.com/package/@intuita-inc/filemod/v/2.0.0. Please tell me if this solves your issue.
